# webapp
FROM webapp

MAINTAINER Jeb Trayer <jdtrayer@gmail.com>

USER 0

RUN yum -y install  pytest && yum clean all

# This default user is created in the openshift/base-centos7 image
USER 1001

ADD ./tests /opt/app-tests/

USER 0
RUN chown 1001:1001 /opt/app-tests
USER 1001

CMD ["py.test", "--junitxml=/opt/app-tests/results.xml", "/opt/app-tests/test_app.py"]
